advanced task 101-compile

diff --git a/0x00-python-hello_world/101-compile b/0x00-python-hello_world/101-compile
--- a/0x00-python-hello_world/101-compile
+++ b/0x00-python-hello_world/101-compile
@@ -1,3 +1,18 @@
 #!/bin/bash
 
+
+if [ -z "$PYFILE" ]; then
+  echo "Error: PYFILE environment variable not set."
+  exit 1
+fi
+
+output_file="${PYFILE%.py}.pyc"
+
+
 python3 -m compileall "$PYFILE"
+
+if [ -f "__pycache__/${PYFILE%.py}.cpython-310.pyc" ]; then
+    mv "__pycache__/${PYFILE%.py}.cpython-310.pyc" "$output_file"
+else
+    echo "Error: Compilation failed."
+fi
